Accounts gets it's own app, can't pull dict out of jsonfield :( WORK IN PROGRESS
Smileyrasmus-UCN/final_project pull request #25
Opened 2022-11-21 13:29 UTC by VigtorBr

2022-11-23 08:15 UTC, Smileyrasmus-UCN requested changes
Jeg får følgende fejl når jeg besøger localhost:8000/users:
![image](https://user-images.githubusercontent.com/76094701/203498700-5750bba9-6a4a-4410-8bf7-a4b4818eac57.png)

2022-11-23 09:06 UTC, 1011454MBJ commented
Tror det skyldes alt det med auth, der er lavet på branch issue-17
![image](https://user-images.githubusercontent.com/76095482/203507532-4502fbed-a3ce-4597-9c5e-4b96b01c8725.png)

2022-11-28 09:11 UTC, Smileyrasmus approved these changes
Jeg har ikke testet det, men stoler på det er ok.

2022-11-28 09:13 UTC, Smileyrasmus-UCN approved these changes
Approvede med den forkerte konto :P

2022-11-28 09:14 UTC, merged